### ISSUE TITLE
Duplicate declaration "MyAccount"

### ISSUE THREAD

**Issue by yzgan** [pizzasaurusrex/TestObject#1]
I followed the scripts described in the readme and it showed the following error when i compiled it
```
TypeError: <path>: Duplicate declaration "myAccount"
  5 | const myAccount= require('testobject_api');
> 6 | const myAccount= new TestObject({
    |       ^
```

and it can solved by changing line 5 to the following:
```
const TestObject= require('testobject_api');
```
Please advise and suggest other possible fixes if the above not recommended?

*Note:  package.json with `"testobject_api": "^2.0.0",`

**Comment by pizzasaurusrex** [comment]
good catch.

**Comment by pizzasaurusrex** [comment]
fixed [here](https://github.com/pizzasaurusrex/TestObject/pull/3)
